version: '3.3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /portainer/Files/AppData/Config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    restart: unless-stopped
    privileged: true
    network_mode: host
    ports: 
      - 8123:8123
# environment
#   - DISABLE_JEMALLOC: true
