---
version: "2.1"
services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York                                 # Change this
      - PASSWORD=Alt3rVsc0p#N                                 # Optional
        #- HASHED_PASSWORD=                                 # Optional
      - SUDO_PASSWORD=Alt3rVsc0p#N                       # Optional
        #- SUDO_PASSWORD_HASH=                              # Optional
        #- PROXY_DOMAIN=code-server.my.domain               # Optional
    volumes:
      # Mount additional volumes here
      - /home/pi/code-server/config:/config
    ports:
      - 7443:8443
    restart: unless-stopped
